### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성1 : ndarray, np.array(iterable)
- 행렬의 생성2 : ones, zeros
- 행렬 데이터 선택 : array[x, y, z]
- 행렬 데이터 수정
    - 행렬 데이터 선택
    - =, >, < (값(scala, vetor, matrix))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range : 결과가 ndarray

### 연습문제
- quiz 100 ~ 130까지 랜덤한 숫자를 가지는 8*8 행렬을 만들고
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환

In [2]:
import random
import numpy as np

In [3]:
datas = np.random.randint(100, 130, size=(8, 8))

In [6]:
datas

array([[110, 106, 107, 107, 107, 113, 101, 114],
       [125, 115, 108, 110, 115, 122, 101, 120],
       [118, 123, 115, 103, 109, 126, 111, 108],
       [113, 114, 113, 121, 117, 100, 108, 101],
       [100, 114, 124, 124, 102, 126, 102, 112],
       [100, 114, 106, 118, 122, 119, 126, 126],
       [101, 102, 110, 123, 106, 104, 127, 109],
       [116, 102, 111, 115, 106, 110, 127, 126]])

In [5]:
datas.astype(str)

array([['110', '106', '107', '107', '107', '113', '101', '114'],
       ['125', '115', '108', '110', '115', '122', '101', '120'],
       ['118', '123', '115', '103', '109', '126', '111', '108'],
       ['113', '114', '113', '121', '117', '100', '108', '101'],
       ['100', '114', '124', '124', '102', '126', '102', '112'],
       ['100', '114', '106', '118', '122', '119', '126', '126'],
       ['101', '102', '110', '123', '106', '104', '127', '109'],
       ['116', '102', '111', '115', '106', '110', '127', '126']],
      dtype='<U11')

In [7]:
for number in datas:
    if int(number) % 3 == 0:
        number = 'fiz'
    elif int(number) % 5 == 0:
        number = 'buz'
    elif int(number) % 15 == 0:
        number = 'fbz'

TypeError: only size-1 arrays can be converted to Python scalars

In [8]:
data1 = np.array([1, 2, 3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [14]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성

idx3 = datas % 3 == 0
idx5 = datas % 5 == 0
idx15 = datas % 15 == 0

In [16]:
# 데이터 타입을 str 으로 변환

datas.dtype

dtype('int32')

In [17]:
result = datas.astype("str")

In [18]:
# T, F 행렬을 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [22]:
result[idx3]

array(['fiz', 'fiz', 'fbz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz',
       'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz',
       'fiz', 'fiz', 'fiz', 'fiz'], dtype='<U11')

In [23]:
result[idx3] = 'fiz'
result[idx5] = 'buz'
result[idx15] = 'fbz'

In [24]:
result

array([['buz', '106', '107', '107', '107', '113', '101', 'fiz'],
       ['buz', 'buz', 'fiz', 'buz', 'buz', '122', '101', 'fbz'],
       ['118', 'fiz', 'buz', '103', '109', 'fiz', 'fiz', 'fiz'],
       ['113', 'fiz', '113', '121', 'fiz', 'buz', 'fiz', '101'],
       ['buz', 'fiz', '124', '124', 'fiz', 'fiz', 'fiz', '112'],
       ['buz', 'fiz', '106', '118', '122', '119', 'fiz', 'fiz'],
       ['101', 'fiz', 'buz', 'fiz', '106', '104', '127', '109'],
       ['116', 'fiz', 'fiz', 'buz', '106', 'buz', '127', 'fiz']],
      dtype='<U11')

### 연습문제
- 1 ~ 20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [25]:
datas = np.random.randint(1, 20, (5, 5))

In [26]:
datas

array([[17,  7,  5, 19, 18],
       [ 6,  1, 12,  7,  6],
       [14, 13,  7, 11,  5],
       [14,  1, 19, 11,  9],
       [ 7,  3,  5, 11, 10]])

In [27]:
min_num, max_num = np.min(datas), np.max(datas)

In [28]:
min_num

1

In [29]:
max_num

19

In [30]:
idx_min = min_num == datas
idx_max = max_num == datas

In [31]:
idx_min

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [32]:
result = datas.astype("str")

In [33]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"

In [34]:
result

array([['17', '7', '5', 'MAX', '18'],
       ['6', 'MIN', '12', '7', '6'],
       ['14', '13', '7', '11', '5'],
       ['14', 'MIN', 'MAX', '11', '9'],
       ['7', '3', '5', '11', '10']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [35]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [36]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

### 연습문제
- 30세 연봉이 $100,000 이고 60세의 연봉이 $1,000,000 일 때
- 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [37]:
age_30 = 100000
age_60 = 1000000

In [38]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [40]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정함
- rand : 균등분포로 난수를 생성
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- shuffle : 행렬 데이터를 섞어 준다.
- choice : 특정 확률로 데이터를 선택

In [42]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [44]:
np.random.rand(10)

array([0.85397529, 0.49423684, 0.84656149, 0.07964548, 0.50524609,
       0.0652865 , 0.42812233, 0.09653092, 0.12715997, 0.59674531])

In [45]:
np.random.randn(10)

array([-0.33882197, -0.23618403, -0.63765501, -1.18761229, -1.42121723,
       -0.1534952 , -0.26905696,  2.23136679, -2.43476758,  0.1127265 ])

In [46]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[9, 6, 4, 1],
       [1, 3, 9, 9],
       [3, 7, 6, 7]])

In [47]:
np.random.shuffle(r)
r

array([[1, 3, 9, 9],
       [9, 6, 4, 1],
       [3, 7, 6, 7]])

In [65]:
result=r.reshape(12, 1)

In [66]:
np.random.shuffle(result)

In [67]:
result

array([[1],
       [3],
       [4],
       [3],
       [1],
       [9],
       [9],
       [6],
       [9],
       [7],
       [7],
       [6]])

In [68]:
result.reshape(3, 4)

array([[1, 3, 4, 3],
       [1, 9, 9, 6],
       [9, 7, 7, 6]])

In [70]:
# choice
# python random 은 마지막 수 포함, numpy randint 마지막 수 불포함

np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])
# 확률을 할당할 수 있음, 순서대로 0, 1, 2, 3, 4에 해당되므로 1은 안 나옴

array([3, 4, 3, 3, 2, 4, 0, 4, 2, 2])

In [72]:
# unique
numbers, counts = np.unique(r, return_counts=True)
print(numbers, counts)

[1 3 4 6 7 9] [2 2 1 2 2 3]


### 3. 행렬 데이터의 결합
- concatenate

In [73]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [74]:
# 세로 결합
na1

array([[0, 8, 5],
       [4, 2, 9]])

In [75]:
na2

array([[7, 1],
       [9, 2],
       [1, 0]])

In [76]:
na3

array([[7, 1, 8],
       [9, 0, 7],
       [0, 5, 2]])

In [78]:
np.concatenate((na1, na3))
# np.concatenate() axis = 0 세로 결합이라는 뜻, 1이면 가로 결합

array([[0, 8, 5],
       [4, 2, 9],
       [7, 1, 8],
       [9, 0, 7],
       [0, 5, 2]])

In [79]:
np.concatenate((na2, na3), axis=1)

array([[7, 1, 7, 1, 8],
       [9, 2, 9, 0, 7],
       [1, 0, 0, 5, 2]])

In [81]:
# c_, r_ 로도 결합이 가능
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [82]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])