In [8]:
import numpy as np

data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])

In [4]:
# variance code

def variance(data):
    
    avg = np.average(data)
    var = 0
    
    for num in data:
        var += (num - avg)**2
        
    return var/len(data)

In [8]:
variance(data1), variance(data2), variance(data1)**0.5, variance(data2)**0.5

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [9]:
np.var(data1), np.var(data2), np.std(data1), np.std(data2)

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [10]:
p_data1 = np.random.randint(60, 100, int(1E5))
p_data2 = np.random.randint(60, 100, int(1E5))
p_data2[-5:]

array([93, 74, 74, 79, 68])

In [13]:
# 일반함수

%time
variance(p_data1), variance(p_data2)

Wall time: 0 ns


(133.22178033511045, 133.41952859110128)

In [14]:
# numpy

%time
np.var(p_data1), np.var(p_data2)

Wall time: 0 ns


(133.22178033510002, 133.4195285911)

In [31]:
def covariance(data_1, data_2):
    avg1 = np.average(data_1)
    avg2 = np.average(data_2)
    covar = 0
    
    for num in data_1, data_2:
        covar += (num1 - avg1)(num2 - avg2)
        
    return covar/len(data_1)-1

In [32]:
covariance(data1, data2)

ValueError: too many values to unpack (expected 2)

In [29]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])
data3 = np.array([80, 85, 100, 90, 95])
data4 = np.array([100, 90, 70, 90, 80])

In [25]:
np.cov(data1, data2)
#[data1과 data1, data1과 data2],
#[data2와 data1, data2와 data2]

array([[ 62.5 ,  93.75],
       [ 93.75, 157.5 ]])

In [26]:
np.cov(data1, data2)[0, 1]

93.75

In [30]:
np.cov(data3, data4)[0, 1]

-87.5

In [41]:
data5 = np.array([800, 850, 1000, 900, 950])
data6 = np.array([1000, 900, 700, 900, 800])
np.cov(data5, data6)[0, 1]

-8750.0

In [42]:
# correlation coefficient function

np.corrcoef(data1, data2)[0, 1],\
np.corrcoef(data3, data4)[0, 1],\
np.corrcoef(data5, data6)[0, 1]

(0.9449111825230682, -0.970725343394151, -0.970725343394151)

In [43]:
np.corrcoef(data1, data2)[0, 1] ** 2,\
np.corrcoef(data1, data4)[0, 1] ** 2

(0.892857142857143, 0.9423076923076923)

### 6. 프리미어리그 데이터 상관계수 분석
- 2016년 프리미어리그 성적에서 득점과 실점 데이터 중에 승점에 영향을 더 많이 준 데이터는?

In [1]:
import pandas as pd

In [2]:
!ls datas

2014_p.csv
2014_s.csv
premierleague.csv
train.csv


In [4]:
df = pd.read_csv("datas/premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [9]:
# 득점
gf = np.array(df["gf"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31], dtype=int64)

In [11]:
# 실점
ga = np.array(df["ga"])
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56], dtype=int64)

In [10]:
# 승점
points = np.array(df["points"])
points

array([100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
        41,  40,  37,  36,  33,  33,  31], dtype=int64)

In [15]:
data1, data2 = np.corrcoef(gf, points)[0, 1] ** 2, np.corrcoef(ga, points)[0, 1] ** 2

In [16]:
round(data1, 2), round(data2, 2)

(0.87, 0.76)